version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_UID}
    image: ${PROJECT}:latest
    container_name: ${PROJECT}
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - type: bind
        source: ${HOME}/${WORKING_DIR}/${PROJECT}
        target: /home/${USER}/${PROJECT}
      - type: bind
        source: ${HOME}/.ssh
        target: /home/${USER}/.ssh
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/${USER}/.gitconfig
    working_dir: /home/${USER}/${PROJECT}
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


